apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pve-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pve-exporter
  template:
    metadata:
      labels:
        app: prometheus-pve-exporter
    spec:
      containers:
        - name: prometheus-pve-exporter
          image: prompve/prometheus-pve-exporter            
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "1000m"  
          volumeMounts:
            - mountPath: /etc/prometheus
              name: nfs
              subPath: applications/prometheus-pve-exporter/volumes
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 15
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"    
          effect: "NoExecute"    
          tolerationSeconds: 15          
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: truenas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter-service
  annotations:
    metallb.io/address-pool: internal-pool
    metallb.io/allow-shared-ip: "shared-ip"
spec:
  type: LoadBalancer
  selector:
    app: prometheus-pve-exporter
  ports:
    - name: http
      port: 9221
      targetPort: 9221
      protocol: TCP