apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipallowlist-internal
  namespace: kube-system
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.1.0/24
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: skipverify
  namespace: kube-system
spec:
  insecureSkipVerify: true